name: GolangBuild
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Check go Version
        run: go version

      - name: GoBuild
        run: go build ./cmd/main

